from collections.abc import Iterable
from typing import Any

from rest_framework import fields as drf_fields

from restflow.filters.fields import (
    BooleanField,
    ChoiceField,
    DateField,
    DateTimeField,
    DecimalField,
    DurationField,
    EmailField,
    Field,
    FloatField,
    IntegerField,
    IPAddressField,
    ListField,
    MultipleChoiceField,
    OrderField,
    StringField,
    TimeField,
)
from restflow.filters.filters import FilterSet

LOOKUP_DESCRIPTIONS = {
    "exact": "equals",
    "iexact": "equals (case-insensitive)",
    "contains": "contains",
    "icontains": "contains (case-insensitive)",
    "startswith": "starts with",
    "endswith": "ends with",
    "istartswith": "starts with (case-insensitive)",
    "iendswith": "ends with (case-insensitive)",
    "gt": "is greater than",
    "gte": "is greater than or equal to",
    "lt": "is less than",
    "lte": "is less than or equal to",
    "in": "is one of",
    "range": "is in range",
    "isnull": "is null",
    "regex": "matches regex",
    "iregex": "matches regex (case-insensitive)",
    "date": "date is",
    "year": "year is",
    "month": "month is",
    "day": "day is",
    "week": "week is",
    "week_day": "weekday is",
    "quarter": "quarter is",
    "hour": "hour is",
    "minute": "minute is",
    "second": "second is",
    "search": "matches full-text search",
    "trigram_similar": "is trigram-similar to",
    "unaccent": "matches (accent-insensitive)",
    "overlaps": "overlaps with",
    "contained_by": "is contained by",
}


def build_filterset_parameters(filterset_class: type[FilterSet]) -> list[dict[str, Any]]:
    """Return OpenAPI parameter descriptors (one per field) for the given FilterSet class."""
    if filterset_class is None:
        return []
    filterset = filterset_class()
    separator = (
        getattr(filterset.get_options(), "lookup_separator", "__") or "__"
    )
    return list(iterate_field_parameters(filterset, separator))


def iterate_field_parameters(
    filterset: FilterSet, separator: str
) -> Iterable[dict[str, Any]]:
    """Yield one OpenAPI parameter dict per field declared on the FilterSet."""
    for field_name, field in filterset.fields.items():
        yield field_to_parameter(field_name, field, separator)


def field_to_parameter(
    field_name: str, field: Field, separator: str
) -> dict[str, Any]:
    """Build the OpenAPI parameter object for a single FilterSet field."""
    schema = field_to_schema(field)
    parameter: dict[str, Any] = {
        "name": field_name,
        "in": "query",
        "required": bool(getattr(field, "required", False)),
        "schema": schema,
    }
    description = get_field_description(field_name, field, separator)
    if description:
        parameter["description"] = description
    if schema.get("type") == "array":
        parameter["explode"] = False
        parameter["style"] = "form"
    return parameter


def get_field_description(
    field_name: str, field: Field, separator: str
) -> str | None:
    """Compose a human description for a FilterSet field, deriving the lookup verb from the field name suffix."""
    explicit = getattr(field, "help_text", None)
    label = getattr(field, "label", None)
    if not explicit and label and not lookups_autogenerated(field_name, label):
        explicit = label

    is_negated = field_name.endswith("!")
    if explicit and getattr(field, "_explicit_help_text", False):
        return f"exclude where {explicit}" if is_negated else explicit

    name_no_bang = field_name.removesuffix("!")
    base = getattr(field, "_base_field_name", None)
    if not base and separator and separator in name_no_bang:
        base = name_no_bang.split(separator)[0]

    hint = ""
    if (
        base
        and name_no_bang != base
        and separator
        and name_no_bang.startswith(f"{base}{separator}")
    ):
        suffix = name_no_bang[len(base) + len(separator):]
        verb = LOOKUP_DESCRIPTIONS.get(suffix, suffix.replace("_", " "))
        hint = f"{base} {verb}"
    elif is_negated:
        hint = base or name_no_bang

    if is_negated and hint:
        hint = f"exclude where {hint}"

    if explicit and hint:
        return f"{hint} - {explicit}"
    return explicit or hint or None


def lookups_autogenerated(field_name: str, label: str) -> bool:
    """Return True when the field's label is the auto-generated default and adds no information."""
    auto_keep_bang = field_name.replace("_", " ").strip().capitalize()
    auto_strip_bang = (
        field_name.replace("!", "").replace("_", " ").strip().capitalize()
    )
    return label in {auto_keep_bang, auto_strip_bang}


def bool_schema(_field: Field) -> dict[str, Any]:
    return {"type": "boolean"}


def integer_schema(field: Field) -> dict[str, Any]:
    return numeric_schema(field, {"type": "integer"})


def float_schema(field: Field) -> dict[str, Any]:
    return numeric_schema(field, {"type": "number", "format": "float"})


def email_schema(field: Field) -> dict[str, Any]:
    return string_schema(field, fmt="email")


def ip_schema(field: Field) -> dict[str, Any]:
    return string_schema(field, fmt=None)


def datetime_schema(field: Field) -> dict[str, Any]:
    return string_schema(field, fmt="date-time")


def date_schema(field: Field) -> dict[str, Any]:
    return string_schema(field, fmt="date")


def time_schema(field: Field) -> dict[str, Any]:
    return string_schema(field, fmt="time")


def duration_schema(field: Field) -> dict[str, Any]:
    return string_schema(field, fmt="duration")


def plain_string_schema(field: Field) -> dict[str, Any]:
    return string_schema(field, fmt=None)


def numeric_schema(
    field: Field, base: dict[str, Any]
) -> dict[str, Any]:
    schema = dict(base)
    min_v = getattr(field, "min_value", None)
    max_v = getattr(field, "max_value", None)
    if min_v is not None:
        schema["minimum"] = min_v
    if max_v is not None:
        schema["maximum"] = max_v
    return schema


def decimal_schema(field: Field) -> dict[str, Any]:
    schema = numeric_schema(
        field, {"type": "string", "format": "decimal"}
    )
    md = getattr(field, "max_digits", None)
    dp = getattr(field, "decimal_places", None)
    if md is not None:
        schema["x-maxDigits"] = md
    if dp is not None:
        schema["x-decimalPlaces"] = dp
    return schema


def string_schema(field: Field, *, fmt: str | None) -> dict[str, Any]:
    schema: dict[str, Any] = {"type": "string"}
    if fmt:
        schema["format"] = fmt
    max_length = getattr(field, "max_length", None)
    min_length = getattr(field, "min_length", None)
    if max_length is not None:
        schema["maxLength"] = max_length
    if min_length is not None:
        schema["minLength"] = min_length
    return schema


def choice_schema(field: Field) -> dict[str, Any]:
    choices = getattr(field, "choices", None) or {}
    return {"type": "string", "enum": list(choices.keys())}


def multiple_choice_schema(field: Field) -> dict[str, Any]:
    choices = getattr(field, "choices", None) or {}
    return {
        "type": "array",
        "items": {"type": "string", "enum": list(choices.keys())},
        "uniqueItems": True,
    }


def list_schema(field: Field) -> dict[str, Any]:
    child = getattr(field, "child", None)
    if isinstance(child, drf_fields.Field):
        items = field_to_schema(child) if isinstance(child, Field) else {
            "type": "string"
        }
    else:
        items = {"type": "string"}
    return {"type": "array", "items": items}


SCHEMA_DISPATCH: list[tuple[type, Any]] = [
    (OrderField, multiple_choice_schema),
    (ListField, list_schema),
    (MultipleChoiceField, multiple_choice_schema),
    (ChoiceField, choice_schema),
    (BooleanField, bool_schema),
    (IntegerField, integer_schema),
    (FloatField, float_schema),
    (DecimalField, decimal_schema),
    (EmailField, email_schema),
    (IPAddressField, ip_schema),
    (DateTimeField, datetime_schema),
    (DateField, date_schema),
    (TimeField, time_schema),
    (DurationField, duration_schema),
    (StringField, plain_string_schema),
]


def field_to_schema(field: Field) -> dict[str, Any]:
    """Return the OpenAPI schema dict for a FilterSet field, dispatching by field class."""
    for cls, handler in SCHEMA_DISPATCH:
        if isinstance(field, cls):
            return handler(field)
    return {"type": "string"}


def resolve_filterset_class(view) -> type[FilterSet] | None:
    """Resolve a view's FilterSet class, preferring `view.get_filterset_class()` over `view.filterset_class`."""
    getter = getattr(view, "get_filterset_class", None)
    if callable(getter):
        try:
            cls = getter()
            if cls is not None:
                return cls
        except Exception:
            pass
    return getattr(view, "filterset_class", None)
