from typing import Any

from rest_framework.filters import BaseFilterBackend

from restflow.filters.filters import FilterSet
from restflow.spectacular.parameters import (
    LOOKUP_DESCRIPTIONS,
    build_filterset_parameters,
    field_to_parameter,
    field_to_schema,
    get_field_description,
    iterate_field_parameters,
    lookups_autogenerated,
)

__all__ = [
    "LOOKUP_DESCRIPTIONS",
    "RestflowFilterBackend",
    "build_filterset_parameters",
    "field_to_parameter",
    "field_to_schema",
    "get_field_description",
    "iterate_field_parameters",
    "lookups_autogenerated",
]


class RestflowFilterBackend(BaseFilterBackend):
    """
    Plug a restflow `FilterSet` into DRF's filter backend pipeline.

    Looks up `view.filterset_class` (or calls
    `view.get_filterset_class()` if the view defines one) and uses it
    to filter the queryset.
    Example:
        ::

            class ProductView(generics.ListAPIView):
                queryset = Product.objects.all()
                serializer_class = ProductSerializer
                filter_backends = [RestflowFilterBackend]
                filterset_class = ProductFilterSet
    """

    def get_filterset_class(self, view, queryset=None) -> type[FilterSet] | None:
        """Return the `FilterSet` class for the view, preferring `view.get_filterset_class()` over `view.filterset_class` when defined."""
        getter = getattr(view, "get_filterset_class", None)
        if callable(getter):
            return getter()
        return getattr(view, "filterset_class", None)

    def get_filterset(self, request, queryset, view) -> FilterSet | None:
        """Build the `FilterSet` instance for the current request, calling `view.get_filterset(filterset_class)` when the view defines that hook."""
        filterset_class = self.get_filterset_class(view, queryset)
        if filterset_class is None:
            return None
        getter = getattr(view, "get_filterset", None)
        if callable(getter):
            return getter(filterset_class)
        return filterset_class(request=request)

    def filter_queryset(self, request, queryset, view):
        """Apply the resolved `FilterSet` to `queryset` and return the filtered result. No-op when the view has no `FilterSet`."""
        filterset = self.get_filterset(request, queryset, view)
        if filterset is None:
            return queryset
        return filterset.filter_queryset(queryset)

    async def afilter_queryset(self, request, queryset, view):
        """Async version of filter_queryset."""
        filterset = self.get_filterset(request, queryset, view)
        if filterset is None:
            return queryset
        return await filterset.afilter_queryset(queryset)

    def get_schema_operation_parameters(self, view) -> list[dict[str, Any]]:
        """Schema parameter generation is delegated to `restflow.spectacular.parameters.build_filterset_parameters`."""
        return build_filterset_parameters(self.get_filterset_class(view))

    def get_schema_fields(self, view):  # pragma: no cover
        return []
